version: '3.8'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: Myrootpassword123@
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: Password123@
    ports:
      - "3306:3306"
    volumes:
      - mysql-vol:/var/lib/mysql


volumes:
  mysql-vol:
    external: true

